return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "modern",
    spec = {
      { "<leader>e", desc = "Explorer: toggle" },
      { "<leader>E", desc = "Explorer: cwd", icon = { icon = "󰉋 ", color = "blue" } },
      { "<leader>b", group = "buffer" },
      { "<leader>b0", desc = "Buffer: last tab" },
      { "<leader>b1", desc = "Buffer: tab 1" },
      { "<leader>b2", desc = "Buffer: tab 2" },
      { "<leader>b3", desc = "Buffer: tab 3" },
      { "<leader>b4", desc = "Buffer: tab 4" },
      { "<leader>b5", desc = "Buffer: tab 5" },
      { "<leader>b6", desc = "Buffer: tab 6" },
      { "<leader>b7", desc = "Buffer: tab 7" },
      { "<leader>b8", desc = "Buffer: tab 8" },
      { "<leader>b9", desc = "Buffer: tab 9" },
      { "<leader>bd", desc = "Buffer: close" },
      { "<leader>f", group = "find" },
      { "<leader>fb", desc = "Find: buffers" },
      { "<leader>fc", desc = "Find: commands" },
      { "<leader>fd", desc = "Find: diagnostics" },
      { "<leader>ff", desc = "Find: files" },
      { "<leader>fh", desc = "Find: help" },
      { "<leader>fr", desc = "Find: recent files" },
      { "<leader>ft", desc = "Find: todo comments" },
      { "<leader>fT", desc = "Find: todo/fix comments" },
      { "<leader>fw", desc = "Find: word search" },
      { "<leader>g", group = "git" },
      { "<leader>gb", desc = "Git: blame line" },
      { "<leader>gd", desc = "Git: diff file" },
      { "<leader>gg", desc = "Git: lazygit" },
      { "<leader>gp", desc = "Git: preview hunk" },
      { "<leader>gq", desc = "Git: hunks to quickfix" },
      { "<leader>gr", desc = "Git: reset hunk" },
      { "<leader>gR", desc = "Git: reset buffer" },
      { "<leader>gs", desc = "Git: stage hunk" },
      { "<leader>gS", desc = "Git: stage buffer" },
      { "<leader>h", desc = "Dashboard: open", icon = { icon = "󰕮 ", color = "cyan" } },
      { "<leader>l", group = "language", icon = { icon = "󰅩 ", color = "purple" } },
      { "<leader>lc", desc = "Config: open init.lua" },
      { "<leader>ld", desc = "LSP: line diagnostic" },
      { "<leader>lf", desc = "LSP: format" },
      { "<leader>r", group = "refactor" },
      { "<leader>rn", desc = "LSP: rename" },
      { "<leader>t", group = "terminal" },
      { "<leader>tc", desc = "Terminal: close" },
      { "<leader>tn", desc = "Terminal: new bottom split" },
      { "<leader>ts", desc = "Terminal: select" },
      { "<leader>tt", desc = "Terminal: toggle bottom" },
      { "<leader>tT", desc = "Terminal: full buffer" },
      { "<leader>c", group = "code" },
      { "<leader>ca", desc = "LSP: code action" },
      { "<leader>cl", desc = "Trouble: LSP locations" },
      { "<leader>cs", desc = "Trouble: document symbols" },
      { "<leader>x", group = "trouble", icon = { icon = "󱖫 ", color = "green" } },
      { "<leader>xx", desc = "Trouble: diagnostics" },
      { "<leader>xX", desc = "Trouble: buffer diagnostics" },
      { "<leader>xL", desc = "Trouble: location list" },
      { "<leader>xQ", desc = "Trouble: quickfix list" },
      { "[d", desc = "LSP: previous diagnostic" },
      { "]d", desc = "LSP: next diagnostic" },
      { "[c", desc = "Git: previous hunk" },
      { "]c", desc = "Git: next hunk" },
      { "[t", desc = "Todo: previous comment" },
      { "]t", desc = "Todo: next comment" },
      { "ih", desc = "Git: select hunk", mode = { "o", "x" } },
      { "gd", desc = "LSP: definition" },
      { "gD", desc = "LSP: declaration" },
      { "gi", desc = "LSP: implementation" },
      { "gr", desc = "LSP: references" },
      { "K", desc = "LSP: hover" },
      { "<S-h>", desc = "Buffer: previous tab" },
      { "<S-l>", desc = "Buffer: next tab" },
    },
  },
}
